# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 49c532e800726df3fcab6b8c9a1505bcefbb3765ee248f75365b6b05af2a7d4a50c7a7d0ccb506975588044a4763cea539a8bca2941f052d61c4abdd522f6d34

test:
  secret_key_base: e829bfde00cc891b7e3a574ecfe3b1091703f6fb4a92bd752e0f1dbc629d21ac68d923dcbc80afaea75bbf1f59e9cc0d3ab2f3b28f0a63f04e917833ee000a04

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
